### ISSUE TITLE
Inclusion of collaboration field

### ISSUE THREAD

**Issue by mreininghaus** [josephwright/biblatex-phys#11]
It would be nice to have the collaboration field included to produce an output like

[7] K. Abe _et al._ (T2K Collaboration), Phys. Rev. D **88**, 032002 (2013)

from a .bib file entry with a `collaboration = {T2K Collaboration}` line.
This conforms to the instructions given in the [Physical Review Style and Notation Guide](https://publish.aps.org/files/styleguide-pr.pdf) (p. 7) by the APS.

**Comment by mreininghaus** [comment]
any update on this?

**Comment by josephwright** [comment]
This is going to be Biber-only, but I agree it sounds reasonable (sorry it's taken so long to look at it!). I'll see what I can do.

**Comment by mreininghaus** [comment]
Thank you for finally spending efforts on this! Unfortunately, your solution doesn't seem to work just out of the box. The style always takes the "field-undef'ed" branch, regardless of the presence of the collaboration field. From what I read up in the biblatex documentation and stackexchange, it seems to be necessary to modify the data model of biblatex in order to add custom fields.
