### ISSUE TITLE
Surplus space 

### ISSUE THREAD

**Issue by aueelis** [josephwright/biblatex-phys#14]
While citing a software package as `@misc` with `author={{Software Company}}`, I noticed a surplus space directly in front of the company name.

**Comment by josephwright** [comment]
Could you add a full MWE here?

**Comment by aueelis** [comment]
This is an MWE with three citations to actually notice the additional space in the bibliography. The second reference misses the author's given name.

By removing the [lines 57-72 from phys.bbx](https://github.com/josephwright/biblatex-phys/blob/b7b07a6383512e1769eeeed99f9bd60eb4c607ce/phys.bbx#L57-L72) the problem disappears.

**main.tex:**

    \documentclass{article}
    
    \usepackage[style=phys,backend=biber]{biblatex}
    \addbibresource{lib.bib}
    
    \begin{document}
    
    \cite{ref1}
    \cite{ref2}
    \cite{ref3}
    
    \printbibliography
    
    \end{document}

**lib.bib**

    @article{ref1,
      author = {John Doe},
      title = {First ref},
      year = {2000}
    }
    
    @article{ref2, 
      author = {Doe},
      title = {Second ref},
      year = {2001}
    }
    
    @article{ref3,
      author = {John Doe},
      title = {Third ref},
      year = {2002}
    }

**Comment by josephwright** [comment]
Fixed in current release as far as I can see.
