### ISSUE TITLE
Superfluous comma with two-author publications

### ISSUE THREAD

**Issue by tchufnagel** [josephwright/biblatex-phys#18]
Publications with two authors produce bibliography entries with a comma after the first author's name, for example "A. Bonnie, and D. Clyde ... " instead of "A. Bonnie and D. Clyde ..." MWE source files below, with PDF output attached.
[mwe_comma_bug.pdf](https://github.com/josephwright/biblatex-phys/files/1049610/mwe_comma_bug.pdf)

**MWE LaTeX file:**
\documentclass[12pt]{article}
\usepackage[english]{babel}
\usepackage[backend=biber,style=phys]{biblatex}
\addbibresource{mwe.bib}

\begin{document}

This is a test~\cite{OlsonMTA:76}.

\printbibliography

\end{document}

**MWE bib file:**
@article{OlsonMTA:76,
	Author = {Olson, G B and Cohen, M},
	Journal = {Metallurgical Transactions A},
	Number = {11},
	Pages = {1897--1904},
	Title = {A general mechanism of martensitic nucleation},
	Volume = {7},
	Year = {1976}}

**Comment by josephwright** [comment]
This is controlled by `\finalandcomma` so is easy to change. Do you know what the APS do here: both forms are possible.

**Comment by tchufnagel** [comment]
Hi,

Thanks for the quick reply and the pointer to \finalandcomma, which I had not realized was available. But I still think there's a bug in biblatex-phys. I've attached two .tex files, one using style=numeric and one using style=phys. The numeric example omits the comma after the first author, but the phys example does not; the codes are identical other than changing the style invocation.

Best,

Todd Hufnagel

------
Todd Hufnagel
Professor
Department of Materials Science and Engineering
Johns Hopkins University

On Jun 3, 2017, at 9:49 AM, Joseph Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


This is controlled by \finalandcomma so is easy to change. Do you know what the APS do here: both forms are possible.

**Comment by josephwright** [comment]
Could you add `\listfiles` to your input and post the `File list` you get in your `.log` file here? I'm not seeing the issue with and up-to-date system.

**Comment by tchufnagel** [comment]
*File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size12.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
   babel.sty    2016/04/23 3.9r The Babel package
 english.ldf    2012/08/20 v3.3p English support from the babel system
biblatex.sty    2016/05/14 v3.4 programmable bibliographies (PK/JW/AB)
   iftex.sty    2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX,
 and LuaTeX
pdftexcmds.sty    2016/05/10 v0.21 Utility functions of pdfTeX for LuaTeX (HO)
infwarerr.sty    2016/05/16 v1.4 Providing info/warning/error messages (HO)
ifluatex.sty    2016/05/16 v1.4 Provides the ifluatex switch (HO)
 ltxcmds.sty    2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
   ifpdf.sty    2016/05/14 v3.1 Provides the ifpdf switch
etoolbox.sty    2015/08/02 v2.2a e-TeX tools for LaTeX (JAW)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
kvoptions.sty    2016/05/16 v3.12 Key value format for package options (HO)
kvsetkeys.sty    2016/05/16 v1.17 Key value parser (HO)
etexcmds.sty    2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
  logreq.sty    2010/08/04 v1.0 xml request logger
  logreq.def    2010/08/04 v1.0 logreq spec v1.0
  ifthen.sty    2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
 xstring.sty    2013/10/13  v1.7c  String manipulations (C Tellechea)
  blx-dm.def
    phys.dbx
biblatex-dm.cfg
blx-compat.def    2016/05/14 v3.4 biblatex compatibility (PK/JW/AB)
biblatex.def    2016/05/14 v3.4 biblatex compatibility (PK/JW/AB)
standard.bbx    2016/05/14 v3.4 biblatex bibliography style (PK/JW/AB)
 numeric.bbx    2016/05/14 v3.4 biblatex bibliography style (PK/JW/AB)
numeric-comp.bbx    2016/05/14 v3.4 biblatex bibliography style (PK/JW/AB)
    phys.bbx    2016/03/13 v1.0a biblatex bibliography style
numeric-comp.cbx    2016/05/14 v3.4 biblatex citation style (PK/JW/AB)
    phys.cbx    2016/03/13 v1.0a biblatex citation style
biblatex.cfg    
 english.lbx    2016/05/14 v3.4 biblatex localization (PK/JW/AB)
mwe_comma_bug_phys.bbl
 ***********

**Comment by josephwright** [comment]
Several of your files, most notably `biblatex` itself and the `phys` style, are out-of-date: the first step is to update your system.

**Comment by tchufnagel** [comment]
Thanks for the suggestion; that helped.

------
Todd Hufnagel
Professor
Department of Materials Science and Engineering
Johns Hopkins University

On Jun 4, 2017, at 11:03 PM, Joseph Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


Several of your files, most notably biblatex itself and the phys style, are out-of-date: the first step is to update your system.
