### ISSUE TITLE
Keep title capitalisation

### ISSUE THREAD

**Issue by araujoms** [josephwright/biblatex-phys#21]
Would it be possible to add an option for biblatex-phys to keep the title capitalisation as it is, instead of changing everything to lowercase?

I understand that the APS style requires the title to be lowercased, but still the result is rather ugly (in fact APS by default suppresses the title entirely, so one rarely sees the bad result). I use biblatex-phys mainly because it properly handles DOIs and links to the arXiv, so strict compliance with APS is not relevant to me.

The way I found to do this is to add the command `\DeclareFieldFormat{titlecase}{#1}` in the preamble, as described [here](https://tex.stackexchange.com/questions/430483/biblatex-changes-capitalisation-of-titles).

(Unrelated: it would be nice if you could release the next version of biblatex-phys soon, the current one drowns pdflatex with warnings, and this has already been fixed in the git version).

**Comment by josephwright** [comment]
The entire idea of `biblatex` is that end users can change style in their documents, and here we are talking a pretty trivial piece of code. I'm not keen on adding options for every possible change: I think this is best handled in the docs.
