### ISSUE TITLE
Do not print DOI when pages are not given but eid is

### ISSUE THREAD

**Issue by schtandard** [josephwright/biblatex-phys#26]
Some Journals (including the AIP's Journal of Applied Physics and APS' Physical Review Letters) do not number the pages in the issues but rather the papers contained in them, using a unique ID. ([Example][example-paper]) As I understand the `biblatex` documentation, this ID should _not_ got into the `pages` field but rather into `eid` (it's not numbering pages, after all). The field's description reads
> The electronic identifier of an `@article`. This field may replace the pagesfield
for journals deviating from the classic pagination scheme of printed journals by only
enumerating articles or papers and not pages.

Currently, the DOI is printed if `pages` is not given, even if `doi=false` is set. While I see the point of this if the page information is just missing, I think this should not happen, if the journal just doesn't use page numbers and the `eid` is given instead.

[example-paper]: https://doi.org/10.1103/PhysRevLett.103.047001

**Comment by josephwright** [comment]
I'll look to do this: the original ideas predate `eid` so there were pages-or-nothing, you are right that a minor adjustment is in order.
